# Build settings
markdown: kramdown
future: true
#highlighter: pygments
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5
language: 'fa-IR'
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jalalidate
  - jemoji
  - jekyll-jalali
# Site settings
title: "shosseinib"
description: > # knowledge / gnu linux / bioinformatics / clinic 
email: shosseinib@outlook.com
#blog logo
logo: "/assets/images/logo2.jpg"
# blog cover
# cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'shosseinib'
author: 'shosseinib'
#author_image: "/assets/images/logo2.svg"
collections:
  - medium_posts

url: "http://shosseinib.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/
#    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	instagram
#    url:	https://instagram.com/
#    desc:	Follow me
#    share_url:
#    share_title:
#    share_link:

#  - icon:	medium
#    url:	https://medium.com/
#    desc:	Follow me
#    share_url:
#    share_title:
#    share_link:

#  - icon:	vimeo
#    url:	https://virgool.io/
#    desc:	Follow me
#    share_url:
#    share_title:
#    share_link:

#  - icon:	linkedin
#    url:	https://www.linkedin.com/in//
#    desc:	Follow me
#    share_url:
#    share_title:
#    share_link:

